version: 2.1
orbs:
  discord: antonioned/discord@0.1.0
  node: circleci/node@5.0.2
  cypress: cypress-io/cypress@3

jobs:
  chromatic:
      executor: node/default
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: yarn install
        - run: npx chromatic --project-token=$chromatic --exit-zero-on-changes
  unit-test:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ~/.config
            - ./node_modules
      - run: yarn test
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
            - .cache/Cypress
            - project
          root: ~/
  e2e-test:
    executor: cypress/default
    parallelism: 8
    steps:
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          cypress-command: npx cypress run --component --parallel --record
  publish:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Authenticate with NPM and publish
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc && yarn publish --access public
      - discord/status:
          success_only: true
          success_message: ":partying_face: La version :sparkles:${CIRCLE_TAG}:sparkles: de Bubble-craft est disponible :partying_face:"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Configure gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GCLOUD_PROJECT_ID
      # Déploiement sur Google Cloud Run
      - run:
          name: Build
          command: ls -la && gcloud builds submit --region=$REGION --tag $_AR_HOSTNAME/$GCLOUD_PROJECT_ID/$_SERVICE_NAME/$REPO_NAME:$CIRCLE_SHA1
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy $REPO_NAME --image=$_AR_HOSTNAME/$GCLOUD_PROJECT_ID/$_SERVICE_NAME/$REPO_NAME:$CIRCLE_SHA1 --platform=$PLATFORM --region=$REGION --allow-$ALLOW

filters-tag: &filters-tag
  branches:
    ignore: /.*/
  tags:
    only: /.*/

filters-all: &filters-all
  tags:
    only: /.*/

workflows:
  version: 2
  common:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --component
      - install-and-persist:
          name: Install & Persist To Workspace
      - e2e-test:
          filters: *filters-all
          name: Run Tests in Parallel
          requires:
            - Install & Persist To Workspace
      - unit-test :
          filters: *filters-all
      - chromatic :
          filters: *filters-all
      - publish :
          requires:
            - unit-test
          filters: *filters-tag
      - deploy:
          requires:
            - unit-test
            - e2e-test
          filters: *filters-tag
