version: 2.1
orbs:
  discord: antonioned/discord@0.1.0

jobs:
  chromatic:
      docker:
        - image: circleci/node:17
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: yarn install
        - run: npx chromatic --project-token=$chromatic
  unit-test:
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ~/.config
            - ./node_modules
      - run: yarn test
  publish:
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run:
          name: Authenticate with NPM and publish
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc && yarn publish --access public
      - discord/status:
          success_only: true
          success_message: ":partying_face: La version :sparkles:${CIRCLE_TAG}:sparkles: de Ditto est disponible :partying_face:"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
  deploy:
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run: yarn global add caprover
      - run: yarn deploy

filters-tag: &filters-tag
  branches:
    ignore: /.*/
  tags:
    only: /.*/

filters-all: &filters-all
  tags:
    only: /.*/

workflows:
  version: 2
  common:
    jobs:
      - unit-test :
          filters: *filters-all
      - chromatic :
          filters: *filters-all
      - publish :
          requires:
            - unit-test
          filters: *filters-tag
      - deploy:
          requires:
            - unit-test
          filters: *filters-tag
